name: Build and deploy ASP.Net Core app to Azure Web App - InspireMe20250523172014

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # updated .NET version (use your project's version)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Add EF tool to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run EF Core Migrations on Azure DB
        run: dotnet ef database update --project InspireMe.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.PROD_CONNECTION_STRING }}


      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'InspireMe20250523172014'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A58AAAD6FAFD40F18B2624C9F3C8A081 }}
